---
title: "p8105_hw2_jer2243"
author: "Juliet Rowe"
date: "2023-09-27"
output: github_document
---

#Problem 1

## Load tidyverse
```{r}
library(tidyverse)
library(dplyr)
```


## Import and Clean pols-month Data

```{r setup}
pols_df =
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into=c("year", "month", "day"), sep="-") |>
  mutate(
    month = replace(month, month=="01", "January"),
    month = replace(month, month=="02", "February"),
    month = replace(month, month=="03", "March"),
    month = replace(month, month=="04", "April"),
    month = replace(month, month=="05", "May"),
    month = replace(month, month=="06", "June"),
    month = replace(month, month=="07", "July"),
    month = replace(month, month=="08", "August"),
    month = replace(month, month=="09", "September"),
    month = replace(month, month=="10", "October"),
    month = replace(month, month=="11", "November"),
    month = replace(month, month=="12", "December"),
    president = case_when(prez_dem == "1" ~ 'dem',
                          prez_gop == "1" ~ 'gop')) |>
select(-prez_dem, -prez_gop, -day)

pols_df
```

#Import and clean snp dataset

```{r}
snp_df =
  read_csv("fivethirtyeight_datasets/snp.csv") |>
  separate(date, into=c("year", "month", "day"), sep="/") |>
  mutate(
    month = replace(month, month=="1", "January"),
    month = replace(month, month=="2", "February"),
    month = replace(month, month=="3", "March"),
    month = replace(month, month=="4", "April"),
    month = replace(month, month=="5", "May"),
    month = replace(month, month=="6", "June"),
    month = replace(month, month=="7", "July"),
    month = replace(month, month=="8", "August"),
    month = replace(month, month=="9", "September"),
    month = replace(month, month=="10", "October"),
    month = replace(month, month=="11", "November"),
    month = replace(month, month=="12", "December"),
    year = ifelse(as.numeric(year)>= 0 & as.numeric(year) <= 15, as.numeric(year) + 2000, as.numeric(year) + 1900)) |>
select(-day)

snp_df
```

#Import and clean the unemployment dataset
```{r}
unemployment_df =
  read_csv("fivethirtyeight_datasets/unemployment.csv")

unemployment_tidy_data =
  pivot_longer(
    unemployment_df,
    cols = starts_with("Jan") : starts_with("Dec"),
    names_to = "month",
    values_to = "value") |>
  mutate(month=recode(month,
                      Jan = "January",
                      Feb = "February",
                      Mar = "March",
                      Apr = "April",
                      May = "May",
                      Jun = "June",
                      Jul = "July",
                      Aug = "August",
                      Sep = "September",
                      Oct = "October",
                      Nov = "November",
                      Dec = "December"),
         year=Year) |>
  select(year, everything()) |>
  select(-Year)

unemployment_tidy_data

```

##Joining datasets
```{r}
pols_df |>
  mutate(year = as.numeric(year))

snp_df |>
  mutate(year = as.numeric(year))

pols_snp_df = full_join(pols_df, snp_df, by=c("year", "month"))
```


#Problem 2

##Import and clean Mr. Trash Wheel Data

```{r}
library(readxl)
mr_trashwheel_data = read_excel("~/Desktop/p8105_hw2_jer2243/202207 Trash Wheel Collection Data.xlsx", sheet=1, range="A2:N550")

mr_trashwheel_data |>
  mutate(homes_powered = (`Weight (tons)`*500/30))
```

##Import and clean Professor Trash Wheel Data

```{r}
library(readxl)
prof_trashwheel_data = read_excel("~/Desktop/p8105_hw2_jer2243/202207 Trash Wheel Collection Data.xlsx", sheet=2, range="A2:M97")

prof_trashwheel_data |>
  mutate(homes_powered = (`Weight (tons)`*500/30))

```

##Import and clean Gwynnda data

```{r}
library(readxl)
gwynnda_data = read_excel("~/Desktop/p8105_hw2_jer2243/202207 Trash Wheel Collection Data.xlsx", sheet=3, range="A2:K110")

gwynnda_data |>
  mutate(homes_powered = (`Weight (tons)`*500/30))
```

